<HomeScreen>:
    name: 'home'
    BoxLayout:
        orientation: 'vertical'
        
        Label:
            text: 'Escanear Asistencia'
            size_hint: 1, 0.15
            font_size: '24sp'
            color: 0, 0, 0, 1
            bold: True
            canvas.before:
                Color:
                    rgba: 0.9, 0.9, 0.9, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
        
        Button:
            text: 'Iniciar Escaneo'
            size_hint: 0.6, 0.15
            pos_hint: {'center_x': 0.5}
            background_color: 0, 0.7, 0.7, 1
            color: 1, 1, 1, 1 
            font_size: '20sp'
            bold: True
        
        BoxLayout:
            orientation: 'vertical'
            padding: '20dp'
            
            Label:
                text: 'Últimos escaneos:'
                color: 0, 0, 0, 1
                font_size: '18sp'
                size_hint_y: 0.1
            
            ScrollView:
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: '10dp'
                    padding: '10dp'
                    
                    Label:
                        text: 'No hay registros recientes'
                        color: 0.5, 0.5, 0.5, 1
                        italic: True
        
        NavigationBar: