<StudentScreen>:
    name: 'student'
    BoxLayout:
        orientation: 'vertical'
        
        Label:
            text: 'Lista de Alumnos'
            size_hint: 1, 0.15
            font_size: '24sp'
            color: 0, 0, 0, 1
            bold: True
            canvas.before:
                Color:
                    rgba: 0.9, 0.9, 0.9, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
        
        BoxLayout:
            orientation: 'horizontal'
            size_hint: 1, 0.1
            padding: '10dp'
            spacing: '10dp'
            
            Button:
                text: 'Importar Excel'
                background_color: 0.2, 0.7, 0.3, 1
                color: 1, 1, 1, 1
                on_press: root.import_excel()
            
            Button:
                text: '+ Nuevo'
                background_color: 0, 0.7, 0.7, 1
                color: 1, 1, 1, 1
                on_press: root.go_to_add()
        
        ScrollView:
            BoxLayout:
                id: students_list
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: '5dp'
                padding: '10dp'
                
                Label:
                    text: 'Aldahir Leal Pérez'
                    color: 0, 0, 0, 1
                    font_size: '18sp'
                    size_hint_y: None
                    height: '40dp'
        
        NavigationBar: